name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: 30
          max_turns: 10
          allowed_tools:
            - "Bash(git status)"
            - "Bash(git log)"
            - "Bash(git show)"
            - "Bash(git blame)"
            - "Bash(git reflog)"
            - "Bash(git stash list)"
            - "Bash(git stash)"
            - "Bash(git stash pop)"
            - "Bash(git ls-files)"
            - "Bash(git branch)"
            - "Bash(git tag)"
            - "Bash(git diff)"
            - "Bash(git add)"
            - "Bash(git commit)"
            - "Bash(git push)"
            - "Bash(git pull)"
            - "Bash(git fetch)"
            - "Bash(git merge)"
            - "Bash(git rebase)"
            - "Bash(git checkout)"
            - "Bash(git reset --soft)"
            - "Bash(git reset --mixed)"
            - "Bash(git clean -fd)"
            - "Bash(go:*)"
            - "Bash(gofmt:*)"
            - "Bash(golangci-lint:*)"
            - "Bash(just:*)"
            - "Bash(make:*)"
            - "Bash(ls:*)"
            - "Bash(cat:*)"
            - "Bash(head:*)"
            - "Bash(tail:*)"
            - "Bash(find:*)"
            - "Bash(grep:*)"
            - "Bash(sed:*)"
            - "Bash(awk:*)"
            - "Bash(sort:*)"
            - "Bash(uniq:*)"
            - "Bash(wc:*)"
            - "Bash(cut:*)"
            - "Bash(tr:*)"
            - "Bash(mkdir:*)"
            - "Bash(rm:*)"
            - "Bash(cp:*)"
            - "Bash(mv:*)"
            - "Bash(touch:*)"
            - "Bash(pwd:*)"
            - "Bash(which:*)"
            - "Bash(whereis:*)"
            - "Bash(file:*)"
            - "Bash(du:*)"
            - "Bash(df:*)"
            - "Bash(echo:*)"
            - "Bash(printf:*)"
            - "Bash(date:*)"
            - "Bash(whoami:*)"
            - "Bash(id:*)"
            - "Bash(export:*)"
            - "Bash(history:*)"
            - "Bash(tree-sitter:*)"
            - "Bash(npm:*)"
            - "Bash(yarn:*)"
            - "Bash(pnpm:*)"
            - "Bash(apt:*)"
            - "Bash(yum:*)"
            - "Bash(pip:*)"
            - "Bash(pip3:*)"
            - "Bash(tar:*)"
            - "Bash(zip:*)"
            - "Bash(unzip:*)"
            - "Bash(gzip:*)"
            - "Bash(gunzip:*)"
            - "Bash(ping:*)"
            - "Bash(node:*)"
            - "Bash(python:*)"
            - "Bash(python3:*)"
            - "Bash(rust:*)"
            - "Bash(cargo:*)"
            - "Bash(java:*)"
            - "Bash(javac:*)"
            - "Bash(mvn:*)"
            - "Bash(gradle:*)"
            - "Bash(ps:*)"
            - "Bash(top:*)"
            - "Bash(htop:*)"
            - "Bash(lsof:*)"
            - "View"
            - "Edit"
            - "Create"
            - "Delete"
            - "Move"
            - "Copy"
            - "ReadFile"
            - "WriteFile"
            - "DeleteFile"
            - "MoveFile"
            - "CopyFile"
            - "GlobTool"
            - "GrepTool"
            - "BatchTool"
            - "FileSearch"
            - "LS"
            - "ListDir"
            - "SemanticSearch"
            - "CreateDirectory"

