name: Release

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force a release even when not on release branch'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    name: Build Release Binaries
    runs-on: macos-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
          
      - name: Extract current version
        id: version
        run: |
          # Extract current version from the code
          CURRENT_VERSION=$(grep -o 'var Version = "[^"]*"' version.go | cut -d'"' -f2)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Build binaries
        run: |
          mkdir -p artifacts
          VERSION=${{ steps.version.outputs.version }}
          
          # MacOS amd64
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -v -o artifacts/nocmt-darwin-amd64 -ldflags="-s -w -X main.Version=$VERSION" .
          
          # MacOS arm64
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -v -o artifacts/nocmt-darwin-arm64 -ldflags="-s -w -X main.Version=$VERSION" .
          
          # Create checksums
          cd artifacts
          shasum -a 256 * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/*
            LICENSE

  update-homebrew:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: 2mawi2/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap
          
      - name: Download release tarball and calculate SHA
        run: |
          curl -L https://github.com/2mawi2/nocmt/archive/refs/tags/${{ needs.build.outputs.tag }}.tar.gz -o nocmt.tar.gz
          SHA256=$(sha256sum nocmt.tar.gz | awk '{print $1}')
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          
      - name: Update formula
        run: |
          cat > homebrew-tap/Formula/nocmt.rb << EOL
          class Nocmt < Formula
            desc "Tool for removing comments from source code while preserving structure"
            homepage "https://github.com/2mawi2/nocmt"
            url "https://github.com/2mawi2/nocmt/archive/refs/tags/${{ needs.build.outputs.tag }}.tar.gz"
            sha256 "${SHA256}"
            license "MIT"
          
            depends_on "go" => :build
          
            def install
              ENV["CGO_ENABLED"] = "1"
              system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=${{ needs.build.outputs.version }}")
            end
          
            test do
              assert_match "nocmt version", shell_output("#{bin}/nocmt --version")
            end
          end
          EOL
          
      - name: Commit and push updated formula
        run: |
          cd homebrew-tap
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/nocmt.rb
          git commit -m "Update nocmt to ${{ needs.build.outputs.version }}"
          git push

  increment-version:
    needs: [build, update-homebrew]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' || github.event.inputs.force_release == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release
          
      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Increment Version on release branch
        run: |
          # Get current version from the output
          CURRENT_VERSION=${{ needs.build.outputs.version }}
          
          # Parse the version
          IFS='.' read -ra VER_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VER_PARTS[0]}
          MINOR=${VER_PARTS[1]}
          PATCH=$((${VER_PARTS[2]}+1))
          
          # Create new version
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          
          # Create a new version.go file with updated version
          cat > version.go << EOL
          // Package main contains the version information for nocmt
          package main

          // Version is the current version of nocmt
          var Version = "${NEW_VERSION}"
          EOL
          
          # Stage and commit the updated file on release branch
          git add version.go
          git commit -m "Bump version to $NEW_VERSION"
          git push origin release
      
      - name: Merge release to main
        run: |
          git fetch origin main:main
          git checkout main
          git merge --no-ff -m "Merge release branch with version bump" release
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 