name: Release

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force a release even when not on release branch'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config gcc g++ make

      - name: Extract current version
        id: version
        run: |
          # Extract current version from the code
          # Match the format in main.go: var Version = "dev"
          CURRENT_VERSION=$(grep -oP 'var Version = "\K[^"]+' main.go || echo "0.0.1")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Build Linux binaries
        run: |
          mkdir -p artifacts
          VERSION=${{ steps.version.outputs.version }}
          
          # Linux amd64
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="zig cc -target x86_64-linux" go build -v -o artifacts/nocmt-linux-amd64 -ldflags="-s -w -X main.Version=$VERSION" .
          
          # Linux arm64
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux" go build -v -o artifacts/nocmt-linux-arm64 -ldflags="-s -w -X main.Version=$VERSION" .
          
          # Windows amd64
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC="zig cc -target x86_64-windows" go build -v -o artifacts/nocmt-windows-amd64.exe -ldflags="-s -w -X main.Version=$VERSION" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts/
          retention-days: 1

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    needs: build-linux
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Build macOS binaries
        run: |
          mkdir -p artifacts
          VERSION=${{ needs.build-linux.outputs.version }}
          
          # MacOS amd64 (native build on macOS runner)
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -v -o artifacts/nocmt-darwin-amd64 -ldflags="-s -w -X main.Version=$VERSION" .
          
          # MacOS arm64 (cross-compile on macOS runner)
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -v -o artifacts/nocmt-darwin-arm64 -ldflags="-s -w -X main.Version=$VERSION" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: artifacts/
          retention-days: 1

  release:
    name: Create Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts/

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-artifacts
          path: artifacts/
          
      - name: Generate checksums
        run: |
          cd artifacts
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build-linux.outputs.tag }}
          name: Release ${{ needs.build-linux.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/*
            LICENSE

  update-homebrew:
    needs: [build-linux, release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: 2mawi2/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap
          
      - name: Download release tarball and calculate SHA
        run: |
          curl -L https://github.com/2mawi2/nocmt/archive/refs/tags/${{ needs.build-linux.outputs.tag }}.tar.gz -o nocmt.tar.gz
          SHA256=$(sha256sum nocmt.tar.gz | awk '{print $1}')
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          
      - name: Update formula
        run: |
          cat > homebrew-tap/Formula/nocmt.rb << EOL
          class Nocmt < Formula
            desc "Tool for removing comments from source code while preserving structure"
            homepage "https://github.com/2mawi2/nocmt"
            url "https://github.com/2mawi2/nocmt/archive/refs/tags/${{ needs.build-linux.outputs.tag }}.tar.gz"
            sha256 "${SHA256}"
            license "MIT"
          
            depends_on "go" => :build
          
            def install
              ENV["CGO_ENABLED"] = "1"
              system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=${{ needs.build-linux.outputs.version }}")
            end
          
            test do
              assert_match "nocmt version", shell_output("#{bin}/nocmt --version")
            end
          end
          EOL
          
      - name: Commit and push updated formula
        run: |
          cd homebrew-tap
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/nocmt.rb
          git commit -m "Update nocmt to ${{ needs.build-linux.outputs.version }}"
          git push

  increment-version:
    needs: [build-linux, update-homebrew]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' || github.event.inputs.force_release == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Increment Version
        run: |
          # Get current version from the output
          CURRENT_VERSION=${{ needs.build-linux.outputs.version }}
          
          # Parse the version
          IFS='.' read -ra VER_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VER_PARTS[0]}
          MINOR=${VER_PARTS[1]}
          PATCH=$((${VER_PARTS[2]}+1))
          
          # Create new version
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          
          # Update version in main.go (adjust file path as needed)
          sed -i "s/var Version = \"$CURRENT_VERSION\"/var Version = \"$NEW_VERSION\"/" main.go
          
          # Create a branch for the version bump
          git checkout -b version-bump-$NEW_VERSION
          git add main.go
          git commit -m "Bump version to $NEW_VERSION"
          git push origin version-bump-$NEW_VERSION
          
          # Create a pull request
          gh pr create --base main --head version-bump-$NEW_VERSION \
            --title "Bump version to $NEW_VERSION" \
            --body "Automated version bump after release $CURRENT_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 